### ISSUE TITLE
fe/be 전체 Kickoff meetup

### ISSUE THREAD

**Issue by philipjkim** [fantasy-fans-ko/lad-fe#2]
일시: 2021-11-05 (Fri) 10pm
장소: Zoom or Google Meet

논의할 것들

- 자기소개
- 우린 뭘 만들건지에 대한 consensus 맞추기
- 간단하게라도 스펙 확정
- 롤 분배

**Comment by philipjkim** [comment]
제가 생각하는 초기 스펙:

- 사용자 인증 (카카오 계정 로그인)
- 일단 NBA 만 고려 (나중에 MLB, NFL 지원 기능 추가 계획)
- 선수 리스트 보기 (sort by stat columns)
- 여러개의 드래프트 룸 고려하지 않고 로그인했을때 유일한 드래프트룸에 입장
- 드래프트룸에 입장하면 현재 로그인해있는 사용자 리스트 표시, 모두 $200 부여됨
- n명 (ex: 4, 6) 이 동시접속하면 드래프트 시작 버튼 활성화
- 접속한 모든 사용자가 드래프트 시작 버튼을 클릭하면 그 순간부터 드래프트 시작
- 드래프트 순번은 입장한 순서 (or random)
- 선수는 우리 NBA 리그 로스터대로만 선택 (G, G, F, F, C, Util, Util, BN 한팀당 총 8명)
- 자기 순번에 선수 한명, 최초 입찰가 정하고 입찰 시작 (15초 제한)
- 일단 선수가 입찰된 후부터는 비딩 가능 (비딩은 10초 제한, 비딩이 발생하면 그시점부터 다시 10초)
- 선수에 대한 비딩은 (자신이 가진 돈 - 자신의 로스터 중 빈 슬롯 수) 까지 가능 (선수 한명당 최소 $1 로 구매 가능하므로)
- 드래프트 중 누군가가 접속이 끊기면 오토픽이 되어야 함 (오토픽 로직은 무식하게 자기 가진돈을 최대한 사용하는 것으로). 접속이 끊긴 사용자가 선수를 선택해야 하는 경우 남은 선수들 중 득점이나 특정 스탯 기준 가장 높은 선수를 선정
- 모두 모든 선수를 뽑고 나면 화면에 결과 표시 (선수 순서별로 어느 팀이 얼마에 가져갔는지 리스트로)

**Comment by parkgoon** [comment]
지금 단계에서 제 의견은 다음과 같습니다. (frondend 관점에서)
1. @philipjkim 께서 제안하신 초기 스펙에 대한 이견 없으며 구현 단계에서 기술적 한계(??)에 직면할 시 조정해가며 진행하면 좋을 것 같습니다.
2. 개인적으로 antd 기반으로 화면 구성 및 데이터 초기 렌더링 정도는 프랙티스가 되어 있는데 이 후 구현 필요한 로직은 고민이 되네요. @toddlee1  께서 제시된 초기 스펙 상으로 구현되어야 하는 frontend 개발 단계 대략적으로 제시 가능하실까요? (아무래도 현업이시나보니 고견이 있으실듯요)
3. (2)항 통하여 수립된 초안을 가지고 킥오프 미팅하면 backend 콤비와의 소통이 더욱 원활하지 싶습니다.
4. 개발자 4인방의 기술역량이 얼마나 되는지 모르겠으나 개발 단계 별 미션을 @philipjkim 께서 제안해 주시고 4인방이 힘을 합쳐 미션 클리어하는 방향으로 진행하면 어떨지 모르겠네요.
5. 미약하나마 CI/CD 구성 경험 있으니 킥오프 시 빌드/배포 구성에 대한 의견을 개진해 보겠습니다. (gitlab-ci , docker , jenkins , nexus 등 유경험)
6. 킥오프 미팅은 backed / frontend 콤비 간에 선 킥오프 후 진행하는 것도 좋을 것 같습니다. (이번 주는 콤비 간 킥오프, 다음 주는 전체 킥오프)

**Comment by philipjkim** [comment]
> 킥오프 미팅은 backed / frontend 콤비 간에 선 킥오프 후 진행하는 것도 좋을 것 같습니다. (이번 주는 콤비 간 킥오프, 다음 주는 전체 킥오프)

동의하고, 그럼 백엔듀오 @kimdg1105 @juyohan 와 프엔듀오 @toddlee1 @parkgoon 이 각각 두분씩 합의하셔서 자체 킥오프 진행하신 후에 이 이슈에 커멘트로 결과 공유 부탁드릴게요~

**Comment by philipjkim** [comment]
> 미약하나마 CI/CD 구성 경험 있으니 킥오프 시 빌드/배포 구성에 대한 의견을 개진해 보겠습니다. (gitlab-ci , docker , jenkins , nexus 등 유경험)

CI/CD 는 따로 안가져가고 GitHub Actions 써보려 하거든요 (be fe 모두). fe 의 경우 [this blog](https://dev.to/dyarleniber/setting-up-a-ci-cd-workflow-on-github-actions-for-a-react-app-with-github-pages-and-codecov-4hnp) 를 참고해주심 되겠네요.

**Comment by juyohan** [comment]
> 동의하고, 그럼 백엔듀오 @kimdg1105 @juyohan 와 프엔듀오 @toddlee1 @parkgoon 이 각각 두분씩 합의하셔서 자체 킥오프 진행하신 후에 이 이슈에 커멘트로 결과 공유 부탁드릴게요~

https://github.com/fantasy-fans-ko/lad-be/issues/3#issue-1036414796

**Comment by philipjkim** [comment]
Yahoo Mock Draft 화면 screenshots:

<img width="1268" alt="Screen Shot 2021-11-05 at 11 10 46 PM" src="https://user-images.githubusercontent.com/197533/140527682-fe19247e-b2b2-48ed-8b6b-5c4fb2916057.png">
<img width="832" alt="Screen Shot 2021-11-05 at 11 12 31 PM" src="https://user-images.githubusercontent.com/197533/140527711-425b7e30-cfa9-4b3c-82fc-76e7ce9c6d35.png">
<img width="829" alt="Screen Shot 2021-11-05 at 11 12 40 PM" src="https://user-images.githubusercontent.com/197533/140527713-f553659a-674d-4f4b-a953-d790fd5612af.png">
<img width="802" alt="Screen Shot 2021-11-05 at 11 12 52 PM" src="https://user-images.githubusercontent.com/197533/140527716-9da00d11-10ef-46d5-a858-f648ddfc554d.png">

**Comment by juyohan** [comment]
https://github.com/fantasy-fans-ko/lad-be/issues/6#issuecomment-962396978

최종 초기 DB 스키마입니다.

**Comment by juyohan** [comment]
일시 : 2021-11-05 (Fri) 10pm
장소 : google meet

# 회의 내용 정리
## FE
- 사용자가 선수를 인수했을 때, 인수한 선수들의 목록을 보고싶다. (My Team에서 포지션과 이름)
- 입찰 할 선수를 선택하는 사용자의 표시를 하자.
- 입찰 할 선수를 선택하는 시간은 30초로 고정.
- 가장 높게 입찰을 하고 있는 사용자의 표시를 하자.
- 입찰이 진행 될 때, 입찰의 가격을 적는 `input` 칸에 입찰된 가격보다 +1이 되도록 하자.
- 다른 사용자가 입찰을 했다면, 낙찰이 될 때까지 제한시간 10초로 고정하자.
- 사용자가 연결이 끊겼을 때, 다른 사람이 대신 입찰 할 선수를 픽하게 해주자.
- 로그인 화면은 카카오 로그인으로 고정을 해두고, 카카오 로그인이 되었다면 닉네임을 적을 수 있게 만들어주자.
- 전체적인 구성은 야후 판타지 드래프트의 화면 구성을 베이스로 두자.
- 10명이 들어온 환경은 어떻게 판단을 할 것인지? → 10명이 채워지지 않아도 시작하게 하자.
- 드래프트가 시작이 되면 텀을 주고 시작되게 하자? (2분 ~ 5분 정도?)

## BE
- 사용자가 접속이 끊겼을 때, 어떻게 인지를 할 것인지에 대해 고민하자.
- 카카오로 로그인을 할 때, 프로필 사진을 가져오게 하자.
- 이메일도 같이 가져와서 드래프트가 끝났을 때, 최종 선택된 사용자들의 선수들을 정리해서 이메일로 전송하자.
- 데이터는 작년 20-21시즌 스탯으로만 하자.
- 선수들의 정보는 스크래핑을 통해 200명 정도를 데이터로 두자.
- `players` 테이블에서 `player_3pt` 와 같은 컬럼은 숫자가 들어가 mysql에서 컬럼명으로 사용이 가능한지 여부를 확인을 해보고 안된다면 `player_three` 로 변경하자.
- 드래프트의 종료 조건은 최종 낙찰 된 선수들의 수를 `count` 해서 마지막 선수까지 된다면 FE에게 끝났다는 응답을 내려주자.

## 추가사항
- 매주 FE와 BE가 모여 개발 진행에 대해 브리핑을 하고, 피드백을 갖는 시간을 갖자. (시간과 날짜는 매주 정하는거로..?? 아마, 금요일 저녁 10시 일듯.)
