### ISSUE TITLE
NBA players mock data 생성

### ISSUE THREAD

**Issue by philipjkim** [fantasy-fans-ko/lad-fe#3]
fe 단에서  mock data 로 사용하거나 DB 에 넣을 작년 (20-21) 정규시즌 기준으로 선수들의 스탯 데이터 (이름, 팀, 포지션, PTS, REB, AST, ST, BLK, TO, TD, FG%, FT%, 3PT%) 뽑기

방법:
- sportradar API 와 같은 api 이용
- 야후 판타지 웹페이지 데이터 파싱

**Comment by juyohan** [comment]
https://github.com/juyohan/yahoo-fantasy.git

html을 다운받은 뒤, 해당 html을 Url로 접근해서 데이터 파싱을 해놨습니다!

**Comment by philipjkim** [comment]
@juyohan 이미 어느정도 bootstraping 해놓은것같으니 위 코드를 fantasy-fans-ko/lad-be 의 베이스코드로 사용해도 될것같네. https://github.com/fantasy-fans-ko/lad-be/issues/1 이슈 assign 했으니 부탁한다!
