### ISSUE TITLE
프론트 화면 - 시나리오 - 기능 초안 스케치 입니다

### ISSUE THREAD

**Issue by parkgoon** [fantasy-fans-ko/lad-fe#4]
2차례 진행된 프듀오 뇌폭풍 활동 시 논의된 끄적임 입니다
[Note Oct 21, 2021.pdf](https://github.com/fantasy-fans-ko/lad-fe/files/7467692/Note.Oct.21.2021.pdf)

**Comment by philipjkim** [comment]
@parkgoon pdf 로 정리 잘 해주셔서 고마워요. 근데 pdf 를 다운받아서 열어서 내용을 확인해야 하니 좀 번거로우시겠지만 pdf page 별로 image 로 따서 여기에 이미지를 바로 embed 해주시면 바로 내용을 볼수 있으니 제일 좋을거같네요. 사실 그림 이외에 text 는 텍스트로 남겨주시는 것이 젤 좋아서, 일단 제가 아래에 제가 원하는 공유방식으로 정리를 해볼게요.

**Comment by philipjkim** [comment]
### 메인 화면 레이아웃

<img width="292" alt="Screen Shot 2021-11-04 at 11 19 14 AM" src="https://user-images.githubusercontent.com/197533/140246661-85b1b084-3c6d-46b2-b30f-66c24421c600.png">

1. ㄱ - 드래프트 페이지 소개 (인트로), 평이한 string 으로 충분 (no event)
2. ㄴ - 사이드바 (종목 및 하부기능 선택). 2depth (종목 > 회차)
    - ex: MLB > 전반기, MLB > 후반기, MLB >. 스페셜
    - event click 시 선수명단 refresh (draft 전: 기본선수명단, draft 후: 구단별 pick 결과 save)
3. ㄷ - 선수 리스트, 메인 기능 영역

### 선수리스트 화면
<img width="361" alt="Screen Shot 2021-11-04 at 11 22 42 AM" src="https://user-images.githubusercontent.com/197533/140247009-12d4e59b-804b-4be9-8e3f-de0f18af1ae1.png">

특이점:
1. 선택한 구단명(판타지구단)을 노출할 1번 컬럼 필요 (edit 가능)
2. stats 은 일부만 기입해도 무방할듯 (선수 식별이 기본적으로 가능한 정도만)
3. focus 이동하면 자동저장되도록

사용자 시나리오:
1. 선수 검색 / 보기 / 정렬 / 선택
2. 구단명 입력 / 저장

TODO: p3~6 정리

**Comment by parkgoon** [comment]
p1, p2 는 v1 이었고 프론리님과 최종 논의된 내용은 p3~ 부터입니다. 내일 한 번 화면상으로 노출되게 편집해서 올려볼께요

**Comment by parkgoon** [comment]
### 1. 화면 구성안
<img width="400" alt="Screen Shot 2021-11-04 at 11 22 42 AM" src="https://user-images.githubusercontent.com/57431867/140444601-ce7dcba8-a757-4e94-bbb6-2e3db463f6f8.png">
<p>콤포넌트 상세</p>
콤포넌트A. 0~30초까지의 카운터 기능과 버튼 기능을 함께 수행 (콤포넌트 오버레이(??) 가능할 것으로 보임) <br>
콤포넌트B. 드래프트가 시작되면 on-air 점멸 되며 버튼 기능을 함께 수행 (admin only control) <br>
콤포넌트C. 현재 Deal 중인 선수 정보 노출 <br>
콤포넌트D. 10개 구단 status(돈 현황,보유 선수 현황) 및 배팅창 제공(돈 입력) <br>
콤포넌트E. 선수 목록 노출, 두개 테이블로 좌측은 선택 가능한 선수 / 우측은 선택한 선수(픽된 순서로) 노출 <br>

### 2. 사용자 시나리오
<img width="400" src="https://user-images.githubusercontent.com/57431867/140444802-953d6c05-6c91-4492-ae60-a91a86f778a5.png">
<p>사용자 타입 정의</p>
1. admin : 드래프트 시작/종료 권한 있음<br>
2. deal user : 옥션 대상 선수를 지정하는 유저(로그인 순서대로 돌아가며 수행)<br>
3. call user : 배팅을 할 수 있는 유저(일반 유저)<br>

### 3. 기능 정의
<img width="400" src="https://user-images.githubusercontent.com/57431867/140444964-637d75c9-3754-4f6f-a8d5-100845d56875.png">
<p>기능 유형</p>
1. 입력 이벤트 : 로그인, 드래프트 개시/종료 입력(클릭), 딜 대상 선수 지정(셀렉트), 콜 머니 입력(인풋) <br>
2. 자동 이벤트 : 카운터, 드래프트 상태, 선수 상태(딜 선택 가능한지 아닌지), 구단 상태(버짓/보유선수), 딜 순서(구단) <br>

### 4. 데이터 정의
<img width="400" src="https://user-images.githubusercontent.com/57431867/140444969-2cc0ca70-aa39-47ed-9dd2-dc0d964be17c.png">
<p>데이터 유형</p>
1. response data : player info, deal order(team name), deal money(max), deal result, update time(+5sec), team budget<br>
2. request data : deal-call money(if max), deal player<br>
3. ui data : counter, team deal-call money<br>

**Comment by toddlee1** [comment]
@parkgoon  미팅때 말씀하신대로 이거 기반으로 태스크 정리를 한번 해볼게요

이거는 제가 잠깐 생각해본건데, 훅에 대해서 많이 사용해보시면 좋을 것 같아서 처음에는 제가 퍼블리싱 작업을 주로 하고 형이 리액트 훅 다루는 작업을 많이 해보시면 어떨까요?

**Comment by philipjkim** [comment]
> @parkgoon 미팅때 말씀하신대로 이거 기반으로 태스크 정리를 한번 해볼게요
> 
> 이거는 제가 잠깐 생각해본건데, 훅에 대해서 많이 사용해보시면 좋을 것 같아서 처음에는 제가 퍼블리싱 작업을 주로 하고 형이 리액트 훅 다루는 작업을 많이 해보시면 어떨까요?

@toddlee1 끼어들어서 죄송한데, 일단 박군님이 현재 상황이 빠르게 배워가며 쳐나가긴 힘드신 상황같으니 토드님이 훅 사용하는 예제 한 페이지를 만들어주시면 박군님이 그걸 보고 따라하는 식으로 하는게 효과적일것같아요.

**Comment by toddlee1** [comment]
## 목표
필수적으로 필요한 기능들이 정상적으로 동작

## 컴포넌트별 기능 
### 0. 레이아웃
전체 페이지에 대한 레이아웃을 정의하는 컴포넌트
### 1. 구단 목록
* 구단 정보 불러오기 (API)
### 2. 선수 목록 (입찰 가능 선수)
* 입찰 가능 선수 불러오기 (API)
* 선수 선택
    * 컴포넌트 5에 선수 상세 정보 표시 (API)
### 3. 선수 목록 (내 입찰 선수)
* 내 입찰 선수 불러오기 (API)
* 포지션 별로 위치 [옵션] (화면)
### 4. 입찰 로그
* 입찰된 선수 목록 불러오기 (API)
### 5. 입찰 중인 선수 정보 or 선택한 선수 정보
* 컴포넌트 2에서 선택된 선수 정보 불러오기 [옵션] (API)
* 입찰 중인 선수 정보 불러오기 (API)
### 6. 타이머 / 버튼
* 타이머 (고민중..)
* 현재 최고가 표시
* 현재 최고가 초과 가격만 입찰 가능하도록 (화면)
* 현재 최고가 + $1 로 Input 자동 채움 [옵션]  (API)

## 개발 진행 방안
### 1. 화면
* 각 컴포넌트 별로 동적 기능 제외한 화면 개발 (금주 중으로 프로토타입)
### 2. API 연동
* API 라이브러리 (axios..) 연동하여 실제 백엔드 환경 기반으로 개발
* 협의 필요
    * 선수 정보 불러오는 API 를 백엔드에서 목적별로 개발할지 (프론트 난이도 매우 쉬워짐)
    * API 하나로 불러와서 프론트에서 필터링할지

## 개발 일정 (계획)
### 1주차 (11/12 ~ 11/14)
* 금주 중으로 화면 (동적 기능 제외) 프로토타입
### 2주차 (11/15 ~ 11/21) : 필수기능 개발
* API Response Type 정의 (백엔드와 논의)
* 컴포넌트 별 필수 기능부터 개발 진행
    * 정보 불러오는 API 연동부터 진행
    * ...
### 3주차 (11/22 ~ 11/28) : 백엔드 연동 및 기능 추가 개발
* 백엔드 연동 테스트 시작
* ...

**Comment by parkgoon** [comment]
- 기존에 논의된 내용을 토대로(화면 배치, 기능 내역 등) 기능 정의 및 개발 일정이 프론리님으로부터 정리 되었습니다.
- 향 후 프론리님의 1차 개발물에 대하여 복제(?)/업데이트 하는 방향으로 프론박은 활동 예정하고 있습니다.
- 프론트 개발 초안이 어느 정도 도출 되었음으로 이 후 진행되는 이슈들은 별도로 관리 하는 것이 좋을 것 같습니다. (본 이슈에 추가 의견 있으실 리오픈해주세요)
